name: Veritas CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Test with pytest
      run: |
        pytest --cov=app tests/
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3

  build:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t veritas:${{ github.sha }} .
    - name: Save Docker image
      run: docker save veritas:${{ github.sha }} > veritas.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: veritas.tar
        retention-days: 1

  deploy-dev:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Download Docker image
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    - name: Load Docker image
      run: docker load < veritas.tar
    - name: Deploy to dev environment
      run: |
        echo "Deploying to dev environment..."
        # Here you would deploy to your dev environment

  deploy-prod:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Download Docker image
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    - name: Load Docker image
      run: docker load < veritas.tar
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        # Here you would deploy to your production environment
